POST http://localhost:3455/auth/register HTTP/1.1
content-type: application/json

{
    "firstName": "test",
    "lastName" : "test",
    "email": "test@gmail.com",
    "password" : "test"
}

###
POST http://localhost:3455/auth/login HTTP/1.1
content-type: application/json

{
    "email": "test@gmail.com",
    "password" : "test"
}

###
POST http://localhost:3455/auth/note HTTP/1.1
content-type: application/json

{
    "title": "hello",
    "content" : "this is a test note"
}